In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/TTC Bus Delay Data since 2025.csv")

In [2]:
df.head()

,_id,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle
0,1,2025-01-01T00:00:00,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442
1,2,2025-01-01T00:00:00,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,NaN,0
2,3,2025-01-01T00:00:00,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,NaN,8546
3,4,2025-01-01T00:00:00,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693
4,5,2025-01-01T00:00:00,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801

In [3]:
df.shape

(93563, 11)

In [5]:
df.dtypes

_id          int64
Date           str
Line           str
Time           str
Day            str
Station        str
Code           str
Min Delay    int64
Min Gap      int64
Bound          str
Vehicle      int64
dtype: object

In [6]:
df.isna().sum()

_id              0
Date             0
Line          1113
Time             0
Day              0
Station          0
Code             0
Min Delay        0
Min Gap          0
Bound        18695
Vehicle          0
dtype: int64

In [8]:
df["Code"].nunique()

73

In [9]:
df["Line"].nunique()

629

In [10]:
df["Code"].value_counts().head(10)

Code
EFO      17837
TFCNO     8265
MFSH      6993
MFDV      6557
TFPD      6282
TFO       5251
MFUS      4134
EFD       3741
SFDP      3445
MFSAN     2546
Name: count, dtype: int64

In [11]:
df["Line"].value_counts().head(10)

Line
52 LAWRENCE WEST     2214
32 EGLINTON WEST     2068
102 MARKHAM ROAD     1766
29 DUFFERIN          1765
7 BATHURST           1694
939 FINCH EXPRESS    1583
54 LAWRENCE EAST     1498
63 OSSINGTON         1490
36 FINCH WEST        1426
116 MORNINGSIDE      1425
Name: count, dtype: int64

In [2]:
code_df = pd.read_csv("../data/raw/Code Descriptions.csv")

In [13]:
code_df.head()

   _id   CODE   DESCRIPTION
0    1    EFB          BODY
1    2  EFCAN  CANCELLATION
2    3    EFD         DOORS
3    4   EFDB   DISC BRAKES
4    5   EFHV  HIGH VOLTAGE

In [3]:
merged_df = df.merge(code_df, left_on="Code", right_on="CODE", how="left")

In [27]:
merged_df.head()

,_id_x,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle,_id_y,CODE,DESCRIPTION
0,1,2025-01-01T00:00:00,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442,15.0,MFESA,NO OPERATOR AVAILABLE DUE TO ESA
1,2,2025-01-01T00:00:00,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,NaN,0,27.0,MFUS,UNABLE TO MAINTAIN SCHEDULE
2,3,2025-01-01T00:00:00,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,NaN,8546,25.0,MFUI,ILL CUSTOMER - TRANSPORTED
3,4,2025-01-01T00:00:00,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693,22.0,MFSAN,UNSANITARY
4,5,2025-01-01T00:00:00,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801,25.0,MFUI,ILL CUSTOMER - TRANSPORTED

In [28]:
merged_df["DESCRIPTION"].value_counts().head(10)

DESCRIPTION
OTHER                                21752
NO OPERATOR AVAILABLE                 8265
USED AS SHUTTLE BUS                   6993
ON DIVERSION                          6557
TTC COLLISION â PROPERTY DAMAGE     6300
OTHER â SWITCH VIOLATION            5251
UNABLE TO MAINTAIN SCHEDULE           4134
DOORS                                 3741
DISORDERLY PATRON                     3445
UNSANITARY                            2546
Name: count, dtype: int64

In [29]:
df.shape

(93563, 11)

In [30]:
merged_df.shape

(93563, 14)

In [25]:
unmatched = df[~df["Code"].isin(code_df["CODE"])]

unmatched_counts = unmatched["Code"].value_counts()

unmatched_counts

Code
MFGD     542
EFCEL    354
EFSD     290
SFL      254
EFFL     244
EFAS     200
EFVIS    157
MFFL     146
EFTI     118
TFOR     102
EFTRM     85
EFWA      78
EFLT      76
EFWS      69
MFIE      54
EFCE      50
MFDI      45
EFVC      43
TFDM      42
EFEX      41
MFAFR     36
EFSE      35
MFBD      33
EFSP      25
EFFS      24
TFUT      23
SFG       20
MFSE      16
MFBIO     12
MFINF     10
MFWR       5
EFBK       4
EFPO       3
Name: count, dtype: int64

In [31]:
df["Min Delay"].describe()

count    93563.000000
mean        20.761914
std         51.461453
min          0.000000
25%          8.000000
50%         12.000000
75%         20.000000
max        999.000000
Name: Min Delay, dtype: float64

In [32]:
df["Min Delay"].value_counts().head(15)

Min Delay
10    16918
0     11873
20     7794
15     6250
8      5842
12     4943
30     4179
9      2878
7      2787
18     2706
6      2306
25     2217
22     2030
16     1844
5      1827
Name: count, dtype: int64

In [33]:
df["Min Delay"].value_counts().sort_index().tail(20)

Min Delay
928    1
932    1
935    1
938    1
940    1
941    1
949    1
950    1
960    1
970    1
971    1
977    1
978    1
980    1
984    1
989    1
991    1
996    2
997    2
999    1
Name: count, dtype: int64

In [34]:
df[df["Min Delay"] >= 120][
    ["Date", "Line", "Time", "Code", "Min Delay", "Min Gap"]
].head(20)

,Date,Line,Time,Code,Min Delay,Min Gap
22,2025-01-01T00:00:00,80 QUEENSWAY,07:46,MFDV,575,595
225,2025-01-03T00:00:00,21 BRIMLEY,08:56,MFDV,124,139
274,2025-01-03T00:00:00,72 PAPE,16:03,MFDV,180,190
303,2025-01-03T00:00:00,54 LAWRENCE EAST,20:00,MFDV,180,186
342,2025-01-04T00:00:00,903 KENNEDY SCARBOROUG,07:18,EFHVA,185,30
377,2025-01-04T00:00:00,29 DUFFERIN,15:40,MFPR,596,611
484,2025-01-05T00:00:00,102D MARKHAM ROAD,20:22,MFDV,221,262
545,2025-01-06T00:00:00,75 SHERBOURNE,13:09,MFDV,123,130
585,2025-01-06T00:00:00,36 FINCH WEST,17:03,MFDV,536,546
663,2025-01-07T00:00:00,75 SHERBOURNE,09:22,MFDV,493,501
937,2025-01-09T00:00:00,41 KEELE,07:23,MFDV,318,328
939,2025-01-09T00:00:00,941 KEELE EXPRESS,07:25,MFDV,144,154
943,2025-01-09T00:00:00,9 BELLAMY,07:43,MFDV,123,151
965,2025-01-09T00:00:00,75 SHERBOURNE,10:55,MFDV,551,558
1015,2025-01-09T00:00:00,84 SHEPPARD WEST,19:27,MFDV,309,329
1034,2025-01-09T00:00:00,96 WILSON,23:28,MFDV,167,187
1036,2025-01-09T00:00:00,54 LAWRENCE EAST,23:53,SFPOL,217,228
1038,2025-01-09T00:00:00,54 LAWRENCE EAST,00:00,SFPOL,217,228
1044,2025-01-10T00:00:00,300 BLOOR-DANFORTH,03:00,MFDV,164,181
1052,2025-01-10T00:00:00,29 DUFFERIN,06:06,MFDV,183,193

In [35]:
zero_delay = df[df["Min Delay"] == 0]

In [36]:
zero_delay["Min Gap"].value_counts().head(10)

Min Gap
0     11803
30       10
10        9
9         6
12        4
15        4
22        3
26        3
20        3
25        3
Name: count, dtype: int64

In [37]:
zero_delay["Code"].value_counts().head(15)

Code
MFUS     2821
SFDP      927
TFPD      911
SFO       879
TFOI      714
MFO       599
MFWEA     593
MFUI      548
MFGD      502
MFDV      472
EFO       452
TFO       414
MFSH      398
MFUIR     386
MFTO      224
Name: count, dtype: int64

In [4]:
merged_df[merged_df["Min Delay"] == 0]["DESCRIPTION"].value_counts().head(15)

DESCRIPTION
UNABLE TO MAINTAIN SCHEDULE                      2821
OTHER                                            1950
TTC COLLISION â PROPERTY DAMAGE                 928
DISORDERLY PATRON                                 927
ON BOARD INJURY                                   714
WEATHER RELATED                                   593
ILL CUSTOMER - TRANSPORTED                        548
ON DIVERSION                                      472
OTHER â SWITCH VIOLATION                        414
USED AS SHUTTLE BUS                               398
ILL CUSTOMER â TRANSPORTATION DECLINED          386
ILL OPERATOR & NON CHARGEABLE OPERATOR ISSUES     224
ASSAULT â PATRON                                104
HELD DUE TO POLICE INVESTIGATION                   86
PROPULSION                                         64
Name: count, dtype: int64

Goal:
Predict Min Delay for a newly reported TTC bus incident.

Target:
Min Delay

Initial features:
Date
Time
Day
Line
Station
Code
Bound

Excluded:
_id
Min Gap
Vehicle
DESCRIPTION

In [6]:
df["Date"].head()

0    2025-01-01T00:00:00
1    2025-01-01T00:00:00
2    2025-01-01T00:00:00
3    2025-01-01T00:00:00
4    2025-01-01T00:00:00
Name: Date, dtype: str

In [7]:
df["Time"].head()

0    02:15
1    02:15
2    02:40
3    02:43
4    03:05
Name: Time, dtype: str

In [8]:
model_df = df[
    [
        "Date",
        "Time",
        "Day",
        "Line",
        "Station",
        "Code",
        "Bound",
        "Min Delay",
    ]
].copy()

In [9]:
model_df["Date"] = pd.to_datetime(model_df["Date"])
model_df["month"] = model_df["Date"].dt.month

In [10]:
model_df["hour"] = model_df["Time"].str.split(":").str[0].astype(int)

In [11]:
model_df["Line"] = model_df["Line"].fillna("UNKNOWN")
model_df["Bound"] = model_df["Bound"].fillna("UNKNOWN")

In [12]:
model_df = model_df.drop(columns=["Date", "Time"])

In [13]:
X = model_df.drop(columns=["Min Delay"])
y = model_df["Min Delay"]

In [14]:
model_df.head()

,Day,Line,Station,Code,Bound,Min Delay,month,hour
0,Wednesday,102 MARKHAM ROAD,WARDEN STATION,MFESA,N,20,1,2
1,Wednesday,65 PARLIAMENT,KIPLING STATION,MFUS,UNKNOWN,0,1,2
2,Wednesday,64 MAIN,BROADVIEW STATION,MFUI,UNKNOWN,0,1,2
3,Wednesday,100 FLEMINGDON PARK,OVERLEA AND THORNCLIFF,MFSAN,N,17,1,2
4,Wednesday,34 EGLINTON EAST,EGLINTON AND DON MILLS,MFUI,W,20,1,3

In [15]:
model_df.dtypes

Day            str
Line           str
Station        str
Code           str
Bound          str
Min Delay    int64
month        int32
hour         int64
dtype: object

In [16]:
model_df.shape

(93563, 8)

In [17]:
model_df.isna().sum()

Day          0
Line         0
Station      0
Code         0
Bound        0
Min Delay    0
month        0
hour         0
dtype: int64

In [18]:
timestamp = pd.to_datetime(
    df["Date"].str[:10] + " " + df["Time"]
)

sorted_idx = timestamp.sort_values().index

In [19]:
n = len(sorted_idx)

train_end = int(0.70 * n)
val_end = int(0.85 * n)

train_idx = sorted_idx[:train_end]
val_idx = sorted_idx[train_end:val_end]
test_idx = sorted_idx[val_end:]

In [20]:
X_train = X.loc[train_idx]
y_train = y.loc[train_idx]

X_val = X.loc[val_idx]
y_val = y.loc[val_idx]

X_test = X.loc[test_idx]
y_test = y.loc[test_idx]

In [21]:
print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

Train: (65494, 7)
Validation: (14034, 7)
Test: (14035, 7)

In [22]:
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error

baseline = DummyRegressor(strategy="median")

baseline.fit(X_train, y_train)

val_predictions = baseline.predict(X_val)

baseline_mae = mean_absolute_error(y_val, val_predictions)

print("Baseline MAE:", baseline_mae)

Baseline MAE: 15.027647142653557

In [23]:
categorical_features = [
    "Day",
    "Line",
    "Station",
    "Code",
    "Bound",
]

numeric_features = [
    "month",
    "hour",
]

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features,
        ),
        (
            "numeric",
            "passthrough",
            numeric_features,
        ),
    ]
)

In [25]:
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline

model = Pipeline(
    steps=[
        ("preprocessing", preprocessor),
        ("regressor", Ridge(alpha=1.0)),
    ]
)

In [26]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Day', 'Line', 'Station',
                                                   'Code', 'Bound']),
                                                 ('numeric', 'passthrough',
                                                  ['month', 'hour'])])),
                ('regressor', Ridge())])

In [27]:
val_predictions = model.predict(X_val)

ridge_mae = mean_absolute_error(y_val, val_predictions)

print("Ridge MAE:", ridge_mae)

Ridge MAE: 15.049481835707267

In [28]:
from xgboost import XGBRegressor

xgb_model = Pipeline(
    steps=[
        ("preprocessing", preprocessor),
        (
            "regressor",
            XGBRegressor(
                n_estimators=400,
                max_depth=6,
                learning_rate=0.05,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42,
                n_jobs=-1,
            ),
        ),
    ]
)

In [29]:
xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Day', 'Line', 'Station',
                                                   'Code', 'Bound']),
                                                 ('numeric', 'passthrough',
                                                  ['month', 'hour'])])),
                ('regressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=0.8, device=N...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=6, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=400, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [30]:
xgb_predictions = xgb_model.predict(X_val)

xgb_mae = mean_absolute_error(y_val, xgb_predictions)

print("Baseline MAE:", baseline_mae)
print("Ridge MAE:", ridge_mae)
print("XGBoost MAE:", xgb_mae)

Baseline MAE: 15.027647142653557
Ridge MAE: 15.049481835707267
XGBoost MAE: 14.324959754943848

In [31]:
test_predictions = xgb_model.predict(X_test)

test_mae = mean_absolute_error(y_test, test_predictions)

print("Validation MAE:", xgb_mae)
print("Test MAE:", test_mae)

Validation MAE: 14.324959754943848
Test MAE: 14.288134574890137

In [5]:
from toronto_transit_ml_platform.data import load_data, split_data
from toronto_transit_ml_platform.features import prepare_features
df = load_data('../data/raw/TTC Bus Delay Data since 2025.csv')
train, val, test = split_data(df)
print(train.shape, val.shape, test.shape)

(65494, 12) (14034, 12) (14035, 12)

In [6]:
train_model_df = prepare_features(train)
val_model_df = prepare_features(val)
test_model_df = prepare_features(test)

In [7]:
print(train_model_df.shape)
print(train_model_df.columns)

(65494, 7)
Index(['Day', 'Line', 'Code', 'Bound', 'month', 'hour', 'Min Delay'], dtype='str')